[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GMOS_LIA_Setup"
version = "0.0.7"
description = "Setup to control and test GMOS gas sensor"
authors = [
  { name = "Eli Zeltser", email = "elizeltser97@gmail.com" }
]
readme = "README.rst"
requires-python = ">=3.8"

dependencies = [
  "pyvisa",
  "pyserial",
  "numpy",
  "matplotlib",
  "pytest",
  "ruff",
  "pyright"
]

[project.optional-dependencies]
lint = ["ruff"]
typecheck = ["pyright"]

[tool.setuptools]
package-dir = {"" = "python/sources"}

[tool.setuptools.packages.find]
where = ["python/sources"]

[tool.pytest.ini_options]
testpaths = ["python/tests"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = ["F405"]
