[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GMOS_LIA_Setup"
version = "0.0.5"
description = "Setup to control and test GMOS gas sensor"
authors = [
  { name = "Eli Zeltser", email = "elizeltser97@gmail.com" }
]
readme = "README.rst"
requires-python = ">=3.8"

dependencies = [
  "pyvisa",
  "numpy",
  "matplotlib",
  "pytest",
  "pyright",
  "ruff",
  "black",
  "debugpy"
]

[project.optional-dependencies]
lint = ["ruff>=0.11.11"]
typecheck = ["pyright"]

[project.scripts]
LIATesterCLI = "GMOS_LIA.entry_points:cli"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = ["F405"]
